#!/usr/bin/env bash

# Make sure zsh is installed.
. install_zsh.sh

# Make sure we have ruby 
sudo apt install ruby
sudo apt install ruby-dev

# Install colorls
sudo gem install colorls

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

(cd "${DOTBOT_DIR}" && git submodule update --init --recursive)
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

chsh -s /usr/bin/zsh